// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evrtqrhinquavsrsctot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2cnRxcmhpbnF1YXZzcnNjdG90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMTc5ODMsImV4cCI6MjA2MDc5Mzk4M30.9E94njsZ8vGroMf-KfVRmeY29wMR6CNKdB3L0O5Llsc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);